### ISSUE TITLE
Inquiry about the data format

### ISSUE THREAD

**Issue by CongFu92** [wenhuchen/KB-Reasoning-Data#1]
Hi,
Could you please explain the format of the data files.
For example,
people@person@nationality#/m/023zsh#/m/09c7w0:-1#/m/07c5l:-1#/m/0kpys:-1#/m/0b90_r:-1#/m/0d060g:-1#/m/01n7q:-1#/m/07ssc:1#/m/0f8l9c:-1#/m/0345h:-1#/m/02jx1:-1#/m/05rgl:-1

The "@" and "#" seems to be separators? 
1 and -1 seems to indicate the labels?
What's the meaning of the remaining part?

**Comment by wenhuchen** [comment]
Hi,

I have added the explanation into the front page README, thank you for your remind.
