### ISSUE TITLE
Evaluation of Link Prediction using KBE

### ISSUE THREAD

**Issue by sahisnu** [wenhuchen/KB-Reasoning-Data#2]
Hi,

Thanks for releasing the data of your paper. The approach is very interesting.

Just for a clarification, I saw you have provided a set of sampled negative entities in the validation and test files in each dataset along the positive one for each (h, r, ?) queries.  So, while testing the learned KBE model, we evaluate the ranking performance only on this candidate set of one positive and a set of negative tail entities ? or on full entity set of the graph.

I mean if the KB has say 14k entities, for each query (h, r, ?), we generate 14k candidate triples using each of those 14k entities and the model has to rank the positive entity "t_pos" among those 14k candidate ones.....( I guess other KBE evaluation methods like TransE, DistMult etc. generate candidate set on full graph ...right? ...which is really computationally expensive to test on large graphs)..

Sorry if I'm missing something here..

**Comment by wenhuchen** [comment]
Thank you for your interests in the paper:
1. I evaluate on the set of provided entities, not the whole entity set, which is the standard approach in the community.
2. The same as above, we follow the previous papers, none of them are using the whole entity set.

**Comment by sahisnu** [comment]
Thanks for the response and the clarification....Really appreciate it!
